### ISSUE TITLE
Cannot connect to Elasticsearch 

### ISSUE THREAD

**Issue by josephbleroy** [ServerCentral/praeco#59] opened 2018-11-14 06:28 UTC
I'm running into an issue when connecting to Elasticsearch, or so it seems.

I set my `export PRAECO_ELASTICSEARCH="127.0.0.1"` and ran `docker-compose up`. 

Here's the errors I'm presented with the following issues:

`elasticsearch.exceptions.ConnectionError: ConnectionError (HTTPConnectionPool (host='elasticsearch', port=9200)`

There's a bunch more errors which are roughly the same (connection error based). Unfortunately I cannot copy and paste the error output (corporate network restrictions). My `elasticsearch. yml` is configured as `network.host: localhost`, so I should have no issue using 127.0.0.1 as the Elasticsearch location. 

Eventually the amount of connection errors causes ElastAlert to exit. I also tried to set elasticsearch's location manually in `api.conf.json` and `elastalert.yaml`, but still have the same issues. 

Any thoughts or guidance is greatly appreciated.

Thank you.

**Comment by johnsusek** [comment] 2018-11-14 17:22
What is the output of this command in terminal?

`curl http://$PRAECO_ELASTICSEARCH:9200`

The es_host value `config/elastalert.yaml` and `api.conf.json` shouldn't be changed from 'elasticsearch', as this is the hostname of es _within the context of the docker network_. The hostname 'elasticsearch' within the docker network is replaced by your $PRAECO_ELASTICSEARCH env variable, because of this entry in docker-compose.yml:
```
    extra_hosts:
      - 'elasticsearch:${PRAECO_ELASTICSEARCH}'
```

But I have not tried this with 127.0.0.1, this might be resolving to localhost within the docker container... let me know what your curl output is and we'll go from there.

**Comment by johnsusek** [comment] 2018-11-14 17:54
Thinking about this more, the container is indeed probably trying to communicate with 127.0.0.1 within the context of the docker container, which would cause this error.

The fix would be to set PRAECO_ELASTICSEARCH to your machine's ip address instead of localhost. For example if your machine has an ip address of 192.168.1.120:

```
export PRAECO_ELASTICSEARCH=192.168.1.120
```

Also make sure elasticsearch is listening on 0.0.0.0 and/or 192.168.1.120, instead of only listening on 127.0.0.1.

Try that and let me know how it works.

**Comment by josephbleroy** [comment] 2018-11-15 01:20
> curl http://$PRAECO_ELASTICSEARCH:9200

I set `export PRAECO_ELASTICSEARCH="127.0.0.1"` and the output is:

```
{
  "name": "<name>",
  "cluster_name": "<cluster name>",
  "cluster_uuid": "<cluster uuid>",
  "version": {
    "number": "6.4.0",
    "build_flavor": "default",
    "build_type": "rpm",
    "build_hash": "595516e",
    "build_date": "<build date>",
    "build_snapshot": false,
    "lucene_version": "7.4.0",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  },
  "tagline": "You Know, for Search"
}
```

**Comment by johnsusek** [comment] 2018-11-15 14:51
Instead of 127.0.0.1 for PRAECO_ELASTICSEARCH, trying using the internal IP
of your machine.

Enter `ifconfig | grep "inet "` into a terminal to get your machine's
internal IP address.

**Comment by johnsusek** [comment] 2018-11-15 16:54
I've just stood up an elasticsearch instance on my local machine, and launched it with the following network.host option to bind to my local network ip:
`elasticsearch -E network.host=_site_`

I then changed PRAECO_ELASTICSEARCH to the bound ip, and confirmed praeco can communicate with this ES instance. 

Note I didn't have to change any praeco/elastalert config files, the above two steps are all that are required to get a local ES instance working.

If you are still having problems, it could indeed be a firewall or SELinux.

**Comment by josephbleroy** [comment] 2018-11-16 02:13
No problem! Hoping that I can dig a little deeper in the coming weeks to help improve your documentation for different network / host environments.

**Closed** 2018-11-19 15:59 UTC
